[package]
name = "soccer-sim"
version = "0.1.0"
edition = "2018"


[dependencies]
serde_json = "1.0.68"
scraper = "0.12.0"
rand = "0.8.4"
reqwest = { version = "0.11.6", features = ["blocking", "json"] }
serde = { version = "1.0.130", features = ["derive"] }
